## GENERATED by tools/unity_defs_to_gdscript.py -- do not edit by hand.
##
## Real tuning values extracted from the Unity AssetBundle asset
## `"definitions_assets_all_59ef5631b247f971deb04b3ee736e040.bundle"`
## profile `"KartPhysicsHandlingDefault"` of `"Atlas.Gameplay.Kart.KartPhysicsHandling"`.
##
## These are the game's OWN numbers, recovered from the shipped
## ScriptableObjects -- not estimates. Regenerate with:
##   python3 tools/unity_defs_to_gdscript.py <bundle> Atlas.Gameplay.Kart.KartPhysicsHandling KartPhysicsHandlingDefault kart_physics_handling_data.gd
##
## Curves carry the full keyframe set (time, value, in/out slope, weights).

extends Resource

const SOURCE_BUNDLE := "definitions_assets_all_59ef5631b247f971deb04b3ee736e040.bundle"
const PROFILE_ID := "KartPhysicsHandlingDefault"
const SOURCE_CLASS := "Atlas.Gameplay.Kart.KartPhysicsHandling"


## Build a Curve from raw keyframes [time, value, inSlope, outSlope, inW, outW].
## Weights are accepted for format stability but ignored: every keyframe in this
## game's curves uses Unity's neutral 1/3, and Godot 4's Curve has no per-point
## weight setter. Elements are cast explicitly -- indexing an untyped Array
## yields Variant, and inferring from Variant is an error in Godot 4.7.
static func _curve(points: Array) -> Curve:
	var c := Curve.new()
	if points.is_empty():
		return c
	# CRITICAL: Godot's Curve clamps every added point to min/max domain and
	# min/max value, which both default to 0..1. These curves live in absolute
	# game units (time up to 47, values up to 40), so without widening the
	# ranges first every keyframe silently collapses onto the corner and the
	# whole curve is destroyed -- with no error at all.
	var t_lo := INF
	var t_hi := -INF
	var v_lo := INF
	var v_hi := -INF
	for p in points:
		var arr := p as Array
		t_lo = minf(t_lo, float(arr[0])); t_hi = maxf(t_hi, float(arr[0]))
		v_lo = minf(v_lo, float(arr[1])); v_hi = maxf(v_hi, float(arr[1]))
	# Pad so end tangents are not clipped at the boundary.
	var span := maxf(t_hi - t_lo, 0.001)
	c.min_domain = t_lo - span * 0.02
	c.max_domain = t_hi + span * 0.02
	var vspan := maxf(v_hi - v_lo, 0.001)
	c.min_value = v_lo - vspan * 0.1
	c.max_value = v_hi + vspan * 0.1
	for p in points:
		var arr2 := p as Array
		c.add_point(
			Vector2(float(arr2[0]), float(arr2[1])),
			float(arr2[2]), float(arr2[3]),
			Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c


## Unity stores a "no weighting" tangent as 1/3; every keyframe in this game's
## curves uses exactly that, so weights are simply ignored on export.
static func _default_curve() -> Curve:
	return _curve([[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0, 0.0]])



# --- scalar tuning values (79) ---
const AIR_ROT_SPEED_RATIO: float = 0.3
const BOOST: float = 0.8
const BOOST_DURATION: float = 1.1
const BOOST_SPEED_OFFSET: float = 10.0
const BRAKING: float = 21.0
const COLLISION_ENTER_COOLDOWN: float = 0.25
const CRASH_SPEED_THRESHOLD: float = 17.0
const DRIFT_IN_BOOST_ACCUMULATION_FACTOR: float = 2.0
const DRIFT_OUT_BOOST_ACCUMULATION_FACTOR: float = 0.9
const DRIFT_SPEED_MIN: float = 16.0
const DRIFT_STEER_MAX_DEFAULT: float = 1.17
const DRIFT_STEER_MIN_DEFAULT: float = 0.2425
const DRIFT_STEER_NEUTRAL_DEFAULT: float = 0.5275
const DRIFT_VISUAL_ANGLE_OFFSET: float = 37.0
const DRIFT_VISUAL_ANGLE_SPEED_IN: float = 54.0
const DRIFT_VISUAL_ANGLE_SPEED_OUT: float = 69.0
const DRIFT_VISUAL_YAW_VEL_MAX: float = 5.0
const FASTER_KART_BOUNCE_MAX: float = 12.0
const FASTER_KART_BOUNCE_MIN: float = 2.7
const GLIDING_BOOST_ACCEL_FACTOR: float = 1.0
const GLIDING_PITCH_DOWN_MAX: float = 0.9
const GLIDING_PITCH_SPEED: float = 0.3
const GLIDING_PITCH_STABILISATION: float = 1.0
const GLIDING_PITCH_UP_MAX: float = 20.0
const GLIDING_RATIO: float = 0.35
const GLIDING_RATIO_PITCH_UP: float = 0.92
const GLIDING_ROLL_MAX: float = 32.0
const GLIDING_ROLL_SPEED: float = 0.895
const GLIDING_ROLL_STABILISATION: float = 1.0
const GLIDING_SPEED_PITCH_UP: float = 24.0
const GLIDING_TORQUE: float = 48.0
const GLIDING_UPDRAFT_FORCE: float = 5.2
const GLIDING_YAW_FROM_ROLL: float = 0.9625
const GLIDING_YAW_SPEED: float = 0.18
const HIT_STATE_STEER_CAP: float = 0.25
const HOP_BOOST_DURATION: float = 0.5
const HOP_BOOST_GRAVITY_SCALE: float = 0.68
const HOP_BOOST_RATIO: float = 0.2
const HOP_BOOST_SPEED_THRESHOLD: float = 16.0
const HOP_FORCE: float = 9.75
const HOP_GRAVITY_SCALE: float = 2.75
const HOP_TIMER: float = 0.5
const IMPACT_SPEED_THRESHOLD: float = 7.0
const INITIAL_STEERINGLOCK: float = 0.8
## _kartPhysicsInputConfig = {'_maxAngleVirtualSteeringWheel': 165.0, '_glidingPitchUpDeadZone': 0.800000011920929, '_glidingPitchUpDeadZoneAngle': 60.0, '_glidingPitchDownDeadZone': 0.800000011920929, '_glidingPitchDownDeadZoneAngle': 60.0, '_brakeDeadZone': 0.7250000238418579, '_brakeDeadZoneAngle': 87.5, '_disableBrakeOnDrift': 1, '_disableReverse': 1, '_extraSteerEnabled': 0}   (structured value, not a float)
const KART_TO_KART_SEPARATION_THRESHOLD: float = 99.0
const KART_TO_STATIC_BOUNCE: float = 0.18625
const KART_TO_STATIC_BOUNCE_MAX: float = 14.0
const KART_TO_STATIC_BOUNCE_MIN: float = 7.0
const KART_TO_STATIC_COLLISION_ENTER_SEPARATION_THRESHOLD: float = 99.0
const KART_TO_STATIC_COLLISION_STAY_SEPARATION_THRESHOLD: float = 0.3
const KART_TO_STATIC_SPEED_PENALTY_FACTOR: float = 0.485
const KART_TO_STATIC_SPEED_PENALTY_MIN_THRESHOLD: float = 16.0
const LATERAL_AIR_GRIP: float = 2.0
const LOST_CONTROL_TIMER_ON_CRASH: float = 0.26625
const MID_AIR_BOOST_ACCEL_FACTOR: float = 0.2
const ROT_SPEED_DRIFT_RATIO: float = 0.9
const ROTATE_TO_SURFACE_MAX_ANGLE: float = 30.0
const ROTATE_TO_SURFACE_SPEED: float = 10.0
const ROTATE_TO_VERTICAL_IN_AIR_SPEED: float = 1.15
const SLOPE_COMPENSATION_ANGLE_MAX: float = 60.0
const SLOPE_COMPENSATION_ANGLE_START: float = 45.0
const SLOPE_COMPENSATION_DOWN: float = 1.0
const SLOPE_COMPENSATION_UP: float = 1.0
const SLOWER_KART_BOUNCE_MAX: float = 21.0
const SLOWER_KART_BOUNCE_MIN: float = 3.5
const SMALL_BOOST_SPEED_OFFSET: float = 2.4
const SMALL_LANDING_SPEED_VERTICAL: float = 15.0
const SPEED_HARD_CAP: float = 55.0
const STEER_MIN_TO_DRIFT: float = 0.1
const STEERINGLOCK_RELEASE_TIME: float = 0.8
const TIRE_GRIP: float = 3.992
const TIRE_GRIP_DRIFT: float = 2.1
const TIRE_GRIP_DRIFT_MAX_STEER: float = 12.0
const TURN_SPEED_COMPENSATION: float = 0.1025
const TURN_SPEED_DRIFT_COMPENSATION: float = 0.9
const TURN_SPEED_DRIFT_SIDE_FORCE_RATIO: float = 0.48
const VERTICAL_AIR_GRIP: float = 2.1
const VERTICAL_SPEED_CAP: float = 25.0

# --- curves (5, full keyframes) ---

# _forwardAccelCurve (4 keyframes)
static func curve_forward_accel_curve() -> Curve:
	var c := Curve.new()
	c.min_domain = -0.6
	c.max_domain = 30.6
	c.min_value = 1.77
	c.max_value = 18.93
	c.add_point(Vector2(0.0, 17.5), -3.88, -0.5, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(8.0, 13.5), -0.5, -0.345228, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(20.049999, 9.34), -0.345228, -0.617085, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(30.0, 3.2), -0.617085, -0.2, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c

# _glidingAccelCurve (2 keyframes)
static func curve_gliding_accel_curve() -> Curve:
	var c := Curve.new()
	c.min_domain = -0.94
	c.max_domain = 47.94
	c.min_value = -4.0
	c.max_value = 44.0
	c.add_point(Vector2(0.0, 40.0), -0.262364, -0.262364, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(47.0, 0.0), -0.110784, -0.110784, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c

# _reverseAccelCurve (2 keyframes)
static func curve_reverse_accel_curve() -> Curve:
	var c := Curve.new()
	c.min_domain = -0.2
	c.max_domain = 10.2
	c.min_value = -2.5
	c.max_value = 27.5
	c.add_point(Vector2(0.0, 25.0), -1.12, -2.5, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(10.0, 0.0), -2.5, -1.12, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c

# _rotSpeedFromKartSpeedCurve (5 keyframes)
static func curve_rot_speed_from_kart_speed_curve() -> Curve:
	var c := Curve.new()
	c.min_domain = -0.8
	c.max_domain = 40.8
	c.min_value = 0.894493
	c.max_value = 1.336864
	c.add_point(Vector2(0.0, 1.3), -0.056944, -0.01426, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(9.9375, 1.158286), -0.01426, -0.004648, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(23.5, 1.09525), -0.004648, -0.006304, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(32.5, 1.038518), -0.006304, -0.014288, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(40.0, 0.931357), -0.014288, 0.0, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c

# _rotSpeedFromSteerAngleCurve (2 keyframes)
static func curve_rot_speed_from_steer_angle_curve() -> Curve:
	var c := Curve.new()
	c.min_domain = -0.04
	c.max_domain = 2.04
	c.min_value = 0.9999
	c.max_value = 1.0001
	c.add_point(Vector2(0.0, 1.0), 0.0, 0.0, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	c.add_point(Vector2(2.0, 1.0), 0.0, 0.0, Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c

# --- nested tables (2) ---

# KartHandlingSurfaceTypes (7 entries) -- SKIPPED: contains nested structs, see work/assets/definitions_raw.json

# _driftBoostLevelsTable (3 entries)
# columns: _driftBoostDuration, _driftBoostRatio, _driftBoostType, _driftSteerMax, _driftSteerMin, _driftSteerNeutral, _timeToActivate
static func drift_boost_levels_table_raw() -> Array:
	return [
		[2.9, 0.52, 3.0, 1.21, 0.4425, 0.92, 6.9],
		[1.8875, 0.38, 2.0, 1.19, 0.3425, 0.7125, 4.2],
		[0.775, 0.24, 1.0, 1.17, 0.2425, 0.5275, 2.0],
	]
