## GENERATED by tools/game_defs_to_gdscript.py -- do not edit by hand.
##
## 6 recovered ScriptableObjects from the Unity AssetBundle
## `definitions_assets_all_59ef5631b247f971deb04b3ee736e040.bundle`, Unity 2021.3.56f2.
##
## These are the game's OWN data, read out of its shipped ScriptableObjects.
## Regenerate with:
##   /opt/re-tools/venv/bin/python tools/dump_definitions.py \
##     "<definitions bundle>" work/assets/definitions --pretty
##   /opt/re-tools/venv/bin/python tools/game_defs_to_gdscript.py \
##     work/assets/definitions/definitions.json
##
## Definitions cross-reference each other by id, not by pointer, so these
## dictionaries stay relational: a kart names its season and wheels, a pickup
## table names the usables it can roll. Look a reference up through
## `GameDB.resolve(id)`.

extends RefCounted


## A recovered Unity AnimationCurve, as its raw keyframes wrapped in a
## `__curve__` marker.
##
## Two reasons it is not a live `Curve`: a `const` initialiser must be a
## constant expression and cannot call `make_curve`, and several hundred curves
## exist in the data while a run touches only a handful. `GameDB.curve(value)`
## builds the live Curve on demand.
const CURVE := {"__curve__": [[0.0, 0.0, 0.0, 0.0, 0.3333, 0.3333], [1.0, 1.0, 0.0, 0.0, 0.3333, 0.3333]]}


## True if `value` is recovered curve data rather than an ordinary array/dict.
static func is_curve(value) -> bool:
	return value is Dictionary and value.has("__curve__")


## Build a Godot Curve from recovered Unity keyframes.
## Each key is [time, value, inSlope, outSlope, inWeight, outWeight].
##
## CRITICAL: Godot clamps every added point to the curve's min/max domain and
## min/max value, which BOTH default to 0..1. These curves live in absolute
## game units (time to 47, values to 40), so the ranges are widened BEFORE
## adding points -- otherwise every keyframe silently collapses onto the
## corner and the whole curve is lost with no error at all.
static func make_curve(points: Array) -> Curve:
	var c := Curve.new()
	if points.is_empty():
		return c
	var t_lo := INF
	var t_hi := -INF
	var v_lo := INF
	var v_hi := -INF
	for p in points:
		var a := p as Array
		t_lo = minf(t_lo, float(a[0]))
		t_hi = maxf(t_hi, float(a[0]))
		v_lo = minf(v_lo, float(a[1]))
		v_hi = maxf(v_hi, float(a[1]))
	var tspan := maxf(t_hi - t_lo, 0.001)
	c.min_domain = t_lo - tspan * 0.02
	c.max_domain = t_hi + tspan * 0.02
	var vspan := maxf(v_hi - v_lo, 0.001)
	c.min_value = v_lo - vspan * 0.1
	c.max_value = v_hi + vspan * 0.1
	for p in points:
		var a2 := p as Array
		c.add_point(Vector2(float(a2[0]), float(a2[1])), float(a2[2]),
				float(a2[3]), Curve.TANGENT_FREE, Curve.TANGENT_FREE)
	return c


## Evaluate a recovered curve, falling back to `fallback` outside its domain.
static func sample_curve(points: Array, t: float, fallback: float = 0.0) -> float:
	if points.is_empty():
		return fallback
	var c := make_curve(points)
	# sample_baked() takes no fallback argument and clamps out-of-domain reads
	# to the nearest key, which would hide a caller asking for a time the curve
	# does not cover. A driving curve silently clamped is how you get a kart
	# that refuses to accelerate, so the caller decides instead.
	if t < c.min_domain or t > c.max_domain:
		return fallback
	return c.sample_baked(t)

# ---- handling: 6 definitions ----

const KartPhysicsHandling_KartPhysicsHandlingRaceAI := {
	"m_Name": "KartPhysicsHandlingRaceAI",
	"_id": "KartPhysicsHandlingRaceAI",
	"_forwardAccelCurve": {"__curve__": [[0.0, 17.5, -3.88, -0.375, 0.333333, 0.333333], [8.0, 14.5, -0.375, -0.290456, 0.333333, 0.333333], [20.049999, 11.0, -0.290456, -0.502513, 0.333333, 0.333333], [30.0, 6.0, -0.502513, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 55.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 21.0,
	"_driftSpeedMin": 16.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.6, -0.056944, -0.016604, 0.333333, 0.333333], [9.9375, 1.435, -0.016604, -0.004516, 0.333333, 0.333333], [23.5, 1.37375, -0.004516, -0.006178, 0.333333, 0.333333], [32.5, 1.31815, -0.006178, -0.014007, 0.333333, 0.333333], [40.0, 1.213095, -0.014007, 0.0, 0.0, 0.0]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.0, 0.333333], [2.0, 1.0, 0.0, 0.0, 0.333333, 0.0]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 4.2,
	"_turnSpeedCompensation": 0.1125,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.9,
	"_tireGripDrift": 2.1,
	"_tireGripDriftMaxSteer": 12.0,
	"_driftSteerMinDefault": 0.2425,
	"_driftSteerMaxDefault": 1.12025,
	"_driftSteerNeutralDefault": 0.5275,
	"_turnSpeedDriftCompensation": 0.9,
	"_turnSpeedDriftSideForceRatio": 0.48,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 37.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 10.0,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 16.0,
	"_hopBoostGravityScale": 0.68,
	"_midAirBoostAccelFactor": 0.2,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.4425,
			"_driftSteerMax": 1.13025,
			"_driftSteerNeutral": 0.92
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.3425,
			"_driftSteerMax": 1.12525,
			"_driftSteerNeutral": 0.7125
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.2425,
			"_driftSteerMax": 1.12025,
			"_driftSteerNeutral": 0.5275
		}
	],
	"_driftInBoostAccumulationFactor": 2.05,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 3.5,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 2.7,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.3,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 24.0,
	"_glidingYawSpeed": 0.18,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.3,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 20.0,
	"_glidingPitchDownMax": 0.9,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.35,
	"_glidingRatioPitchUp": 0.92,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 48.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 9.75,
	"_hopTimer": 0.5,
	"_hopGravityScale": 2.75,
	"_initialSteeringlock": 0.86,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.76,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.8,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.8,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 0.0
	}
}
const KartPhysicsHandling_KartPhysicsHandlingShooterExtraSlow := {
	"m_Name": "KartPhysicsHandlingShooterExtraSlow",
	"_id": "KartPhysicsHandlingShooterExtraSlow",
	"_forwardAccelCurve": {"__curve__": [[0.0, 28.5, -3.88, -2.0625, 0.333333, 0.333333], [8.0, 12.0, -2.0625, -0.6875, 0.333333, 0.333333], [16.0, 6.5, -0.6875, -0.366667, 0.333333, 0.333333], [25.0, 3.2, -0.366667, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 32.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 13.0,
	"_driftSpeedMin": 7.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.4, -0.056944, 0.004985, 0.333333, 0.333333], [5.461248, 1.427224, 0.004985, 0.003483, 0.333333, 0.333333], [12.0, 1.45, 0.003483, 0.002213, 0.333333, 0.333333], [20.387381, 1.46856, 0.002213, 0.00067, 0.333333, 0.333333], [30.0, 1.475, 0.00067, -0.0015, 0.333333, 0.333333]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.246372, 1.02256, 0.173686, 0.173686, 0.257814, 0.333333], [1.5, 1.0425, -0.018109, -0.018109, 0.333333, 0.150061], [1.9875, 0.91, -0.86059, -0.86059, 0.091497, 1.0], [2.0, 0.0, -11.075112, -11.075112, 0.048748, 0.333333]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 3.9,
	"_turnSpeedCompensation": 0.65,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.93,
	"_tireGripDrift": 8.0,
	"_tireGripDriftMaxSteer": 8.0,
	"_driftSteerMinDefault": 0.15,
	"_driftSteerMaxDefault": 1.05,
	"_driftSteerNeutralDefault": 0.45,
	"_turnSpeedDriftCompensation": 2.5,
	"_turnSpeedDriftSideForceRatio": 0.5,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 42.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 4.8,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 13.0,
	"_hopBoostGravityScale": 0.975,
	"_midAirBoostAccelFactor": 0.15,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.25,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.65
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.2,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.55
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.15,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.45
		}
	],
	"_driftInBoostAccumulationFactor": 2.0,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 4.0,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 4.0,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.7,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 9.0,
	"_glidingYawSpeed": 0.29,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.55,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 19.0,
	"_glidingPitchDownMax": 22.0,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.49,
	"_glidingRatioPitchUp": 0.97,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 75.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 12.75,
	"_hopTimer": 0.45,
	"_hopGravityScale": 2.85,
	"_initialSteeringlock": 1.0,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.01,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.7,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.7,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 1.0
	}
}
const KartPhysicsHandling_KartPhysicsHandlingDefault := {
	"m_Name": "KartPhysicsHandling",
	"_id": "KartPhysicsHandlingDefault",
	"_forwardAccelCurve": {"__curve__": [[0.0, 17.5, -3.88, -0.5, 0.333333, 0.333333], [8.0, 13.5, -0.5, -0.345228, 0.333333, 0.333333], [20.049999, 9.34, -0.345228, -0.617085, 0.333333, 0.333333], [30.0, 3.2, -0.617085, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 55.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 21.0,
	"_driftSpeedMin": 16.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.3, -0.056944, -0.01426, 0.333333, 0.333333], [9.9375, 1.158286, -0.01426, -0.004648, 0.333333, 0.333333], [23.5, 1.09525, -0.004648, -0.006304, 0.333333, 0.333333], [32.5, 1.038518, -0.006304, -0.014288, 0.333333, 0.333333], [40.0, 0.931357, -0.014288, 0.0, 0.0, 0.0]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.0, 0.333333], [2.0, 1.0, 0.0, 0.0, 0.333333, 0.0]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 3.992,
	"_turnSpeedCompensation": 0.1025,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.9,
	"_tireGripDrift": 2.1,
	"_tireGripDriftMaxSteer": 12.0,
	"_driftSteerMinDefault": 0.2425,
	"_driftSteerMaxDefault": 1.17,
	"_driftSteerNeutralDefault": 0.5275,
	"_turnSpeedDriftCompensation": 0.9,
	"_turnSpeedDriftSideForceRatio": 0.48,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 37.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 10.0,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 16.0,
	"_hopBoostGravityScale": 0.68,
	"_midAirBoostAccelFactor": 0.2,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.4425,
			"_driftSteerMax": 1.21,
			"_driftSteerNeutral": 0.92
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.3425,
			"_driftSteerMax": 1.19,
			"_driftSteerNeutral": 0.7125
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.2425,
			"_driftSteerMax": 1.17,
			"_driftSteerNeutral": 0.5275
		}
	],
	"_driftInBoostAccumulationFactor": 2.0,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 3.5,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 2.7,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.3,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 24.0,
	"_glidingYawSpeed": 0.18,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.3,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 20.0,
	"_glidingPitchDownMax": 0.9,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.35,
	"_glidingRatioPitchUp": 0.92,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 48.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 9.75,
	"_hopTimer": 0.5,
	"_hopGravityScale": 2.75,
	"_initialSteeringlock": 0.8,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.8,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.35,
				"reverseSpeedModifier": 0.4,
				"brakingModifier": 1.3,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.7,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.835
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.8,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.8,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 0.0
	}
}
const KartPhysicsHandling_KartPhysicsHandlingBattle := {
	"m_Name": "KartPhysicsHandlingBattle",
	"_id": "KartPhysicsHandlingBattle",
	"_forwardAccelCurve": {"__curve__": [[0.0, 28.5, -3.88, -2.0625, 0.333333, 0.333333], [8.0, 12.0, -2.0625, -0.6875, 0.333333, 0.333333], [16.0, 6.5, -0.6875, -0.366667, 0.333333, 0.333333], [25.0, 3.2, -0.366667, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 55.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 13.0,
	"_driftSpeedMin": 7.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.4, -0.056944, 0.004985, 0.333333, 0.333333], [5.461248, 1.427224, 0.004985, 0.003483, 0.333333, 0.333333], [12.0, 1.45, 0.003483, 0.002213, 0.333333, 0.333333], [20.387381, 1.46856, 0.002213, 0.00067, 0.333333, 0.333333], [30.0, 1.475, 0.00067, -0.0015, 0.333333, 0.333333]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.246372, 1.02256, 0.173686, 0.173686, 0.257814, 0.333333], [1.5, 1.0425, -0.018109, -0.018109, 0.333333, 0.150061], [1.9875, 0.91, -0.86059, -0.86059, 0.091497, 1.0], [2.0, 0.0, -11.075112, -11.075112, 0.048748, 0.333333]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 3.9,
	"_turnSpeedCompensation": 0.65,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.93,
	"_tireGripDrift": 8.0,
	"_tireGripDriftMaxSteer": 8.0,
	"_driftSteerMinDefault": 0.15,
	"_driftSteerMaxDefault": 1.05,
	"_driftSteerNeutralDefault": 0.45,
	"_turnSpeedDriftCompensation": 2.5,
	"_turnSpeedDriftSideForceRatio": 0.5,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 42.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 4.8,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 13.0,
	"_hopBoostGravityScale": 0.975,
	"_midAirBoostAccelFactor": 0.15,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.25,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.65
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.2,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.55
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.15,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.45
		}
	],
	"_driftInBoostAccumulationFactor": 2.0,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 4.0,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 4.0,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.7,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 9.0,
	"_glidingYawSpeed": 0.29,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.55,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 19.0,
	"_glidingPitchDownMax": 22.0,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.49,
	"_glidingRatioPitchUp": 0.97,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 75.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 12.75,
	"_hopTimer": 0.45,
	"_hopGravityScale": 2.85,
	"_initialSteeringlock": 1.0,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.01,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.7,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.7,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 1.0
	}
}
const KartPhysicsHandling_KartPhysicsHandlingShooter := {
	"m_Name": "KartPhysicsHandlingShooter",
	"_id": "KartPhysicsHandlingShooter",
	"_forwardAccelCurve": {"__curve__": [[0.0, 28.5, -3.88, -2.0625, 0.333333, 0.333333], [8.0, 12.0, -2.0625, -0.6875, 0.333333, 0.333333], [16.0, 6.5, -0.6875, -0.366667, 0.333333, 0.333333], [25.0, 3.2, -0.366667, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 40.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 13.0,
	"_driftSpeedMin": 7.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.4, -0.056944, 0.004985, 0.333333, 0.333333], [5.461248, 1.427224, 0.004985, 0.003483, 0.333333, 0.333333], [12.0, 1.45, 0.003483, 0.002213, 0.333333, 0.333333], [20.387381, 1.46856, 0.002213, 0.00067, 0.333333, 0.333333], [30.0, 1.475, 0.00067, -0.0015, 0.333333, 0.333333]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.0, 1.0, 0.0, 0.0, 0.333333, 0.333333], [1.246372, 1.02256, 0.173686, 0.173686, 0.257814, 0.333333], [1.5, 1.0425, -0.018109, -0.018109, 0.333333, 0.150061], [1.9875, 0.91, -0.86059, -0.86059, 0.091497, 1.0], [2.0, 0.0, -11.075112, -11.075112, 0.048748, 0.333333]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 3.9,
	"_turnSpeedCompensation": 0.65,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.93,
	"_tireGripDrift": 8.0,
	"_tireGripDriftMaxSteer": 8.0,
	"_driftSteerMinDefault": 0.15,
	"_driftSteerMaxDefault": 1.05,
	"_driftSteerNeutralDefault": 0.45,
	"_turnSpeedDriftCompensation": 2.5,
	"_turnSpeedDriftSideForceRatio": 0.5,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 42.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 4.8,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 13.0,
	"_hopBoostGravityScale": 0.975,
	"_midAirBoostAccelFactor": 0.15,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.25,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.65
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.2,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.55
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.15,
			"_driftSteerMax": 1.05,
			"_driftSteerNeutral": 0.45
		}
	],
	"_driftInBoostAccumulationFactor": 2.0,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 4.0,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 4.0,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.7,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 9.0,
	"_glidingYawSpeed": 0.29,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.55,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 19.0,
	"_glidingPitchDownMax": 22.0,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.49,
	"_glidingRatioPitchUp": 0.97,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 75.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 12.75,
	"_hopTimer": 0.45,
	"_hopGravityScale": 2.85,
	"_initialSteeringlock": 1.0,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.01,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.7,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.7,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 1.0
	}
}
const KartPhysicsHandling_KartPhysicsHandlingRace150 := {
	"m_Name": "KartPhysicsHandlingRace150",
	"_id": "KartPhysicsHandlingRace150",
	"_forwardAccelCurve": {"__curve__": [[0.0, 17.5, -3.88, -0.421053, 0.333333, 0.333333], [9.5, 13.5, -0.421053, -0.286897, 0.333333, 0.333333], [24.0, 9.34, -0.286897, -0.472308, 0.333333, 0.333333], [37.0, 3.2, -0.472308, -0.2, 0.333333, 0.333333]]},
	"_reverseAccelCurve": {"__curve__": [[0.0, 25.0, -1.12, -2.5, 0.333333, 0.333333], [10.0, 0.0, -2.5, -1.12, 0.333333, 0.333333]]},
	"_speedHardCap": 55.0,
	"_verticalSpeedCap": 25.0,
	"_braking": 24.0,
	"_driftSpeedMin": 16.0,
	"_slopeCompensationUp": 1.0,
	"_slopeCompensationDown": 1.0,
	"_slopeCompensationAngleStart": 45.0,
	"_slopeCompensationAngleMax": 60.0,
	"_rotSpeedFromKartSpeedCurve": {"__curve__": [[0.0, 1.39, -0.056944, -0.015947, 0.333333, 0.333333], [10.9375, 1.215575, -0.015947, -0.002872, 0.333333, 0.333333], [26.5, 1.170877, -0.002872, -0.006884, 0.333333, 0.333333], [37.5, 1.095155, -0.006884, -0.013053, 0.333333, 0.333333], [48.0, 0.958095, -0.013053, 0.0, 0.0, 0.0]]},
	"_rotSpeedFromSteerAngleCurve": {"__curve__": [[0.0, 1.0, 0.0, 0.0, 0.0, 0.333333], [2.0, 1.0, 0.0, 0.0, 0.333333, 0.0]]},
	"_rotateToSurfaceSpeed": 10.0,
	"_rotateToSurfaceMaxAngle": 30.0,
	"_tireGrip": 4.002,
	"_turnSpeedCompensation": 0.1025,
	"_steerMinToDrift": 0.1,
	"_rotSpeedDriftRatio": 0.92375,
	"_tireGripDrift": 2.1,
	"_tireGripDriftMaxSteer": 12.0,
	"_driftSteerMinDefault": 0.2425,
	"_driftSteerMaxDefault": 1.14,
	"_driftSteerNeutralDefault": 0.5275,
	"_turnSpeedDriftCompensation": 0.8,
	"_turnSpeedDriftSideForceRatio": 0.4,
	"_driftVisualYawVelMax": 5.0,
	"_driftVisualAngleOffset": 37.0,
	"_driftVisualAngleSpeedIn": 54.0,
	"_driftVisualAngleSpeedOut": 69.0,
	"_boostSpeedOffset": 11.0,
	"_boost": 0.8,
	"_boostDuration": 1.1,
	"_smallBoostSpeedOffset": 2.4,
	"_hopBoostRatio": 0.2,
	"_hopBoostDuration": 0.5,
	"_hopBoostSpeedThreshold": 16.0,
	"_hopBoostGravityScale": 0.68,
	"_midAirBoostAccelFactor": 0.2,
	"_glidingBoostAccelFactor": 1.0,
	"_driftBoostLevelsTable": [
		{
			"_driftBoostType": 3.0,
			"_timeToActivate": 6.9,
			"_driftBoostRatio": 0.52,
			"_driftBoostDuration": 2.9,
			"_driftSteerMin": 0.4425,
			"_driftSteerMax": 1.159,
			"_driftSteerNeutral": 0.92
		},
		{
			"_driftBoostType": 2.0,
			"_timeToActivate": 4.2,
			"_driftBoostRatio": 0.38,
			"_driftBoostDuration": 1.8875,
			"_driftSteerMin": 0.3425,
			"_driftSteerMax": 1.152,
			"_driftSteerNeutral": 0.7125
		},
		{
			"_driftBoostType": 1.0,
			"_timeToActivate": 2.0,
			"_driftBoostRatio": 0.24,
			"_driftBoostDuration": 0.775,
			"_driftSteerMin": 0.2425,
			"_driftSteerMax": 1.147,
			"_driftSteerNeutral": 0.5275
		}
	],
	"_driftInBoostAccumulationFactor": 2.0,
	"_driftOutBoostAccumulationFactor": 0.9,
	"_smallLandingSpeedVertical": 15.0,
	"_slowerKartBounceMin": 3.5,
	"_slowerKartBounceMax": 21.0,
	"_fasterKartBounceMin": 2.7,
	"_fasterKartBounceMax": 12.0,
	"_kartToKartSeparationThreshold": 99.0,
	"_kartToStaticBounce": 0.18625,
	"_kartToStaticCollisionEnterSeparationThreshold": 99.0,
	"_kartToStaticCollisionStaySeparationThreshold": 0.3,
	"_kartToStaticBounceMin": 7.0,
	"_kartToStaticBounceMax": 14.0,
	"_kartToStaticSpeedPenaltyFactor": 0.485,
	"_kartToStaticSpeedPenaltyMinThreshold": 16.0,
	"_crashSpeedThreshold": 17.0,
	"_impactSpeedThreshold": 7.0,
	"_lostControlTimerOnCrash": 0.26625,
	"_collisionEnterCooldown": 0.25,
	"_airRotSpeedRatio": 0.3,
	"_rotateToVerticalInAirSpeed": 1.15,
	"_glidingAccelCurve": {"__curve__": [[0.0, 40.0, -0.262364, -0.262364, 0.333333, 0.038483], [47.0, 0.0, -0.110784, -0.110784, 0.042432, 0.333333]]},
	"_glidingSpeedPitchUp": 24.0,
	"_glidingYawSpeed": 0.18,
	"_glidingRollSpeed": 0.895,
	"_glidingPitchSpeed": 0.3,
	"_glidingYawFromRoll": 0.9625,
	"_glidingPitchUpMax": 20.0,
	"_glidingPitchDownMax": 0.9,
	"_glidingRollMax": 32.0,
	"_glidingPitchStabilisation": 1.0,
	"_glidingRollStabilisation": 1.0,
	"_glidingRatio": 0.35,
	"_glidingRatioPitchUp": 0.92,
	"_lateralAirGrip": 2.0,
	"_verticalAirGrip": 2.1,
	"_glidingTorque": 48.0,
	"_glidingUpdraftForce": 5.2,
	"_hopForce": 9.75,
	"_hopTimer": 0.5,
	"_hopGravityScale": 2.75,
	"_initialSteeringlock": 0.855,
	"_hitStateSteerCap": 0.25,
	"_steeringlockReleaseTime": 0.7675,
	"KartHandlingSurfaceTypes": [
		{
			"SurfaceType": 1.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.0,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.0,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 2.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.5,
				"reverseSpeedModifier": 0.6,
				"brakingModifier": 1.2,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.65,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.85
			}
		},
		{
			"SurfaceType": 4.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 3.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 0.95,
					"turnSpeedCompensationModifier": 1.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.02,
				"tireGripDriftMaxModifier": 0.985,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 6.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.0,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.0,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.025,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.05,
					"turnSpeedCompensationModifier": 2.0
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.065,
				"HopForceModifier": 1.0
			}
		},
		{
			"SurfaceType": 5.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 1.03226,
				"reverseSpeedModifier": 1.0,
				"brakingModifier": 1.1,
				"driftSpeedMinModifier": 1.0,
				"surfaceDecelerationFactor": 0.0,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.024,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.003,
					"turnSpeedCompensationModifier": 1.25
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.975
			}
		},
		{
			"SurfaceType": 7.0,
			"KartHandlingSurfaceModifiers": {
				"speedModifier": 0.35,
				"reverseSpeedModifier": 0.4,
				"brakingModifier": 1.3,
				"driftSpeedMinModifier": 999.0,
				"surfaceDecelerationFactor": 0.7,
				"turningModifiers": {
					"rotSpeedFromKartSpeedModifier": 1.175,
					"rotSpeedFromSteerAngleModifier": 1.0,
					"tireGripModifier": 1.12,
					"turnSpeedCompensationModifier": 1.5
				},
				"turnSpeedDriftCompensationModifier": 1.0,
				"rotSpeedDriftRatioModifier": 1.0,
				"tireGripDriftMinModifier": 1.0,
				"tireGripDriftMaxModifier": 1.0,
				"HopForceModifier": 0.835
			}
		}
	],
	"_kartPhysicsInputConfig": {
		"_maxAngleVirtualSteeringWheel": 165.0,
		"_glidingPitchUpDeadZone": 0.8,
		"_glidingPitchUpDeadZoneAngle": 60.0,
		"_glidingPitchDownDeadZone": 0.8,
		"_glidingPitchDownDeadZoneAngle": 60.0,
		"_brakeDeadZone": 0.725,
		"_brakeDeadZoneAngle": 87.5,
		"_disableBrakeOnDrift": 1.0,
		"_disableReverse": 1.0,
		"_extraSteerEnabled": 0.0
	}
}


## Every handling definition, keyed by its recovered id.

const BY_ID := {
	"KartPhysicsHandlingRaceAI": KartPhysicsHandling_KartPhysicsHandlingRaceAI,
	"KartPhysicsHandlingShooterExtraSlow": KartPhysicsHandling_KartPhysicsHandlingShooterExtraSlow,
	"KartPhysicsHandlingDefault": KartPhysicsHandling_KartPhysicsHandlingDefault,
	"KartPhysicsHandlingBattle": KartPhysicsHandling_KartPhysicsHandlingBattle,
	"KartPhysicsHandlingShooter": KartPhysicsHandling_KartPhysicsHandlingShooter,
	"KartPhysicsHandlingRace150": KartPhysicsHandling_KartPhysicsHandlingRace150,
}


## handling definition ids only, for cheap existence checks.

const IDS := [
	"KartPhysicsHandlingRaceAI",
	"KartPhysicsHandlingShooterExtraSlow",
	"KartPhysicsHandlingDefault",
	"KartPhysicsHandlingBattle",
	"KartPhysicsHandlingShooter",
	"KartPhysicsHandlingRace150",
]
