## Authored GLB conversion fixture, NOT recovered game art or Android evidence.
extends SceneTree
var passed := 0
var failed := 0

func _init() -> void:
	call_deferred("run")

func check(label: String, value: bool) -> void:
	passed += int(value)
	failed += int(not value)
	print("  ", "ok " if value else "FAIL ", label)

func finish(scene: Node = null) -> void:
	if scene != null:
		scene.queue_free()
	await process_frame
	print("PASS: %d FAIL: %d" % [passed, failed])
	quit(1 if failed else 0)

func run() -> void:
	var path := OS.get_environment("KART_CONTENT_GLB")
	check("conversion fixture is explicitly supplied", not path.is_empty() and FileAccess.file_exists(path))
	if path.is_empty() or not FileAccess.file_exists(path):
		await finish()
		return
	var document := GLTFDocument.new()
	var state := GLTFState.new()
	var error := document.append_from_file(path, state)
	check("real Godot glTF parser imports the generated bytes", error == OK)
	if error != OK:
		await finish()
		return
	var scene := document.generate_scene(state)
	check("GLB generates an instantiated scene", scene != null)
	if scene == null:
		await finish()
		return
	root.add_child(scene)
	await process_frame
	var source_root: Node3D = scene if scene.name == "FixtureRoot" else scene.find_child("FixtureRoot", true, false)
	check("root translation is reflected exactly once", source_root != null and source_root.position.is_equal_approx(Vector3(-2, 3, 4)))
	var meshes := scene.find_children("*", "MeshInstance3D", true, false)
	var skeletons := scene.find_children("*", "Skeleton3D", true, false)
	var players := scene.find_children("*", "AnimationPlayer", true, false)
	check("one actual renderer is imported", meshes.size() == 1)
	check("one actual skeleton is imported", skeletons.size() == 1)
	check("animation playback infrastructure is imported", players.size() == 1)
	if meshes.size() != 1 or skeletons.size() != 1 or players.size() != 1:
		await finish(scene)
		return
	var renderer: MeshInstance3D = meshes[0]
	var skeleton: Skeleton3D = skeletons[0]
	var player: AnimationPlayer = players[0]
	check("surface is nonempty", renderer.mesh != null and renderer.mesh.get_surface_count() == 1)
	var arrays := renderer.mesh.surface_get_arrays(0)
	var vertices: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
	var uvs: PackedVector2Array = arrays[Mesh.ARRAY_TEX_UV]
	check("all three decoded vertices reach Godot", vertices.size() == 3)
	check("source mesh X is converted once", vertices.has(Vector3(-1, 0, 0)))
	check("UV convention survives import", uvs.has(Vector2(0, 1)))
	check("skin bind count matches the source rig", renderer.skin != null and renderer.skin.get_bind_count() == 1)
	check("bone count matches the source rig", skeleton.get_bone_count() == 1)
	var weights: PackedFloat32Array = arrays[Mesh.ARRAY_WEIGHTS]
	check("skin weights are imported, not just an unskinned mesh", weights.size() == 12 and is_equal_approx(weights[0], 1.0))
	var material: BaseMaterial3D = renderer.mesh.surface_get_material(0)
	check("material is not missing", material != null)
	check("alpha cutoff survives glTF import", material != null and material.transparency == BaseMaterial3D.TRANSPARENCY_ALPHA_SCISSOR and is_equal_approx(material.alpha_scissor_threshold, 0.4))
	check("texture decodes to real pixels", material != null and material.albedo_texture != null and material.albedo_texture.get_width() == 1 and material.albedo_texture.get_height() == 1)
	var motion := ""
	for name: String in player.get_animation_list():
		if name.ends_with("FixtureMotion"):
			motion = name
	check("animation identity is preserved", not motion.is_empty())
	if not motion.is_empty():
		var animation := player.get_animation(motion)
		check("animation duration is one second", is_equal_approx(animation.length, 1.0))
		player.play(motion)
		player.seek(0.5, true)
		check("animation moves the real imported bone at half time", skeleton.get_bone_pose_position(0).is_equal_approx(Vector3(-0.5, 0, 0)))
	await finish(scene)
