#!/usr/bin/env python3
"""Compile recovered track data into a GDScript module.

`build_tracks.py` resolves the maps' scene graphs down to what a race actually
needs: the racing line's control points and per-point road widths, the start
position, pickup spots, respawn locations, surface tags and camera FOV. This
turns that into compile-time GDScript constants.

JSON at runtime is deliberately avoided: a `.json` file is not a Godot
resource, so it is only present in an exported APK if it is added to the
export's include filter -- and when it is missing the game loads with an empty
track and no error. Generated constants cannot go missing.

Usage:
    tracks_to_gdscript.py <tracks.json> <out.gd>
"""

from __future__ import annotations

import argparse
import json
import os
import sys

PRELUDE = '''## GENERATED by tools/tracks_to_gdscript.py -- do not edit by hand.
##
## @@COUNT@@ tracks recovered from the game's map AssetBundles: the racing line
## control points with per-point road widths, start position, pickup spots,
## respawn locations, surface tags and camera FOV.
##
## Source: work/assets/tracks.json, built by tools/build_tracks.py from the
## scenes recovered by tools/extract_assets.py.
##
## Every coordinate is the game's own, in Unity units (1 unit ~= 1 metre).

extends RefCounted

## Human-facing name for a track id.
##
## Ids keep the game's own bundle prefix, which has no separator: a battle map
## is `map_battlebobsfunland`, not `map_battle_bobsfunland`. Matching on
## `map_battle` rather than `map_battle_` is what makes this work -- with the
## underscore, all four battle maps classify as race tracks and then fail every
## check that expects a racing line.
static func display_name(id: String) -> String:
\tvar rest := id.trim_prefix("map_battle")
\tif rest == id:
\t\trest = id.trim_prefix("map_race")
\tif rest == id:
\t\trest = id
\trest = rest.trim_prefix("_")
\treturn rest.replace("_", " ").capitalize()


## True when this track is an arena (battle map) rather than a race circuit.
## Arenas have no racing line, so `track_length()` is 0 and `num_routes()` is 0
## for them -- that is correct, not missing data.
static func is_battle(id: String) -> bool:
\treturn id.begins_with("map_battle")


## Control points of a route, as PackedVector3Array.
## `route` 0 is the main racing line; the rest are the branches and shortcuts
## recovered from the map (StartBoosts, BranchedSpline1..3, JumpRampSplit...).
static func route_points(id: String, route: int = 0) -> PackedVector3Array:
\tvar t := get_track(id)
\tif t.is_empty() or route >= t["routes"].size():
\t\treturn PackedVector3Array()
\tvar out := PackedVector3Array()
\tfor p in t["routes"][route]["points"]:
\t\tout.append(Vector3(p["pos"][0], p["pos"][1], p["pos"][2]))
\treturn out


## Full control point records, including width. Use this when building the road
## mesh: a point's `left`/`right` are how far the road extends either side of
## the spline.
static func route_knots(id: String, route: int = 0) -> Array:
\tvar t := get_track(id)
\tif t.is_empty() or route >= t["routes"].size():
\t\treturn []
\treturn t["routes"][route]["points"]


static func track_length(id: String) -> float:
\treturn float(get_track(id).get("length", 0.0))


static func num_routes(id: String) -> int:
\tvar t := get_track(id)
\treturn t["routes"].size() if not t.is_empty() else 0


static func start_position(id: String) -> Vector3:
\tvar p: Array = get_track(id).get("start", [])
\treturn Vector3(p[0], p[1], p[2]) if p.size() == 3 else Vector3.ZERO


## Pickup spot positions paired with the PickupBox definition each rolls from.
static func pickup_spots(id: String) -> Array:
\treturn get_track(id).get("pickups", [])


## Where a kart respawns after falling off or crashing, nearest-first ordering
## left to the caller.
static func respawn_locations(id: String) -> Array:
\treturn get_track(id).get("respawns", [])


## Surface type counts recovered from ObjectTagBehaviour, keyed by the game's
## own KartHandlingSurfaceType values.
static func surface_histogram(id: String) -> Dictionary:
\treturn get_track(id).get("surfaces", {})


## Glide / boost / hop-boost trigger volumes, as {pos, surface, flags}.
static func triggers(id: String) -> Array:
\treturn get_track(id).get("triggers", [])


static func camera_fov(id: String) -> float:
\tvar c: Array = get_track(id).get("cameras", [])
\treturn float(c[0]["fov"]) if not c.is_empty() else 64.9076


static func has_track(id: String) -> bool:
\treturn not get_track(id).is_empty()
'''


def num(v):
    f = round(float(v), 4)
    if f == int(f):
        return "%.1f" % f
    s = ("%.4f" % f).rstrip("0").rstrip(".")
    return s if s else "0.0"


def vec3(a):
    return "Vector3(%s, %s, %s)" % (num(a[0]), num(a[1]), num(a[2]))


def mat3(a):
    return "Basis(%s)" % ", ".join(vec3(a[i:i + 3]) for i in (0, 3, 6))


def emit_track(t):
    L = []
    name = t["id"].split("_scenes_all_")[0]
    start = t.get("start") or {}
    sp = start.get("pos") or [0.0, 0.0, 0.0]
    # The `"id": {` opener is written by main(); emit_track only contributes
    # the body, so the key is not duplicated.
    L.append('\t\t"name": "%s",' % name)
    L.append('\t\t"bundle": "%s",' % t["id"].split("_scenes_all_")[-1][:8])
    L.append('\t\t"battle": %s,' % ("true" if t["is_battle"] else "false"))
    L.append('\t\t"length": %s,' % num(t["track_length"]))
    L.append('\t\t"laps": %d,' % int(t["laps"]))
    L.append('\t\t"start": %s,' % vec3(sp))
    mb = t.get("map_bounds") or {}
    L.append('\t\t"map_bounds": {"center": %s, "size": %s},'
             % (vec3(mb.get("center", [0, 0, 0])), vec3(mb.get("size", [0, 0, 0]))))
    # routes
    L.append('\t\t"routes": [')
    for s in t["splines"]:
        L.append('\t\t\t{')
        L.append('\t\t\t\t"name": "%s",' % s["name"])
        L.append('\t\t\t\t"loop": %s,' % ("true" if s["loop"] else "false"))
        L.append('\t\t\t\t"points": [')
        for p in s["points"]:
            L.append('\t\t\t\t\t{"pos": %s, "basis": %s, "left": %s, "right": %s},'
                     % (vec3(p["pos"]), mat3(p["rot"]),
                        num(p["left_width"] if p["left_width"] is not None else 5.0),
                        num(p["right_width"] if p["right_width"] is not None else 5.0)))
        L.append('\t\t\t\t],')
        L.append('\t\t\t},')
    L.append('\t\t],')
    # pickups
    L.append('\t\t"pickups": [')
    for p in t["pickup_spots"]:
        L.append('\t\t\t{"pos": %s, "box": "%s", "respawn": %s, "height": %s},'
                 % (vec3(p["pos"]), p["box"], num(p["respawn_time"]),
                    num(p["spawn_height"])))
    L.append('\t\t],')
    # respawns
    L.append('\t\t"respawns": [')
    for r in t["respawn_locations"]:
        L.append('\t\t\t{"pos": %s, "basis": %s},'
                 % (vec3(r["pos"]), mat3(r.get("rot", [1, 0, 0, 0, 1, 0, 0, 0, 1]))))
    L.append('\t\t],')
    # surfaces
    L.append('\t\t"surfaces": {%s},'
             % ", ".join('"%s": %d' % (k, v) for k, v in t["surface_histogram"].items()))
    # triggers
    L.append('\t\t"triggers": [')
    for g in t["triggers"]:
        f = g["flags"]
        L.append('\t\t\t{"pos": %s, "surface": %d, "flags": {"glide": %s, '
                 '"boost": %s, "hop_boost": %s, "hop_gravity": %s}},'
                 % (vec3(g["pos"]), g["surface"],
                    _b(f.get("_isGlideTrigger")), _b(f.get("_isBoostTrigger")),
                    _b(f.get("_isHopBoostTrigger")), _b(f.get("_isHopGravityTrigger"))))
    L.append('\t\t],')
    # cameras
    L.append('\t\t"cameras": [')
    for c in t["cameras"]:
        L.append('\t\t\t{"pos": %s, "fov": %s},' % (vec3(c["pos"]), num(c["fov"])))
    L.append('\t\t],')
    # No closing brace here: main() closes the track's dictionary, because it
    # also opened it.
    return L


LOOKUP = '''

# ---------------------------------------------------------------------------
# Lookup
#
# Tracks are emitted as individual constants and resolved by a match, rather
# than collected into one dictionary constant: the aggregate form does not
# compile (see the note at the emission site). The match is linear over 16
# ids, which is below the point where it is worth building an index.
# ---------------------------------------------------------------------------

static func get_track(id: String) -> Dictionary:
'''


def _b(v):
    return "true" if v else "false"


def _ident(s):
    import re
    s = re.sub(r"[^A-Za-z0-9_]", "_", s)
    return s if re.match(r"[A-Za-z_]", s) else "_" + s


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("tracks_json")
    ap.add_argument("out_gd")
    args = ap.parse_args(argv)

    with open(args.tracks_json) as fh:
        doc = json.load(fh)
    tracks = doc["tracks"]

    out = [PRELUDE.replace("@@COUNT@@", str(len(tracks)))]
    out.append("\nconst IDS := [")
    for t in tracks:
        out.append('\t"%s",' % _ident(t["id"].split("_scenes_all_")[0]))
    out.append("]")
    # One const per track rather than a single aggregate BY_ID.
    #
    # Emitting the whole recovered set as one nested const is the obvious
    # shape, and it does not compile: GDScript rejects the aggregate with
    # "Expected closing } after dictionary elements" even though every value
    # in it is a valid constant expression, and even though each track on its
    # own compiles cleanly. Splitting into per-track constants keeps every
    # declaration small enough to constant-fold, and costs only a lazy lookup.
    out.append("\n\n# --- per-track data (one const each) ---")
    for t in tracks:
        name = _ident(t["id"].split("_scenes_all_")[0])
        out.append("\nconst TRACK_%s := {" % name)
        out.extend(emit_track(t))
        out.append("}")
    out.append(LOOKUP)
    for t in tracks:
        name = _ident(t["id"].split("_scenes_all_")[0])
        out.append('\tif id == "%s":\n\t\treturn TRACK_%s' % (name, name))
    out.append("\treturn {}")

    os.makedirs(os.path.dirname(args.out_gd) or ".", exist_ok=True)
    with open(args.out_gd, "w") as fh:
        fh.write("\n".join(out) + "\n")

    pts = sum(s["point_count"] for t in tracks for s in t["splines"])
    print("wrote %s  (%d tracks, %d control points, %.1f MB)"
          % (args.out_gd, len(tracks), pts, os.path.getsize(args.out_gd) / 1e6))
    return 0


if __name__ == "__main__":
    sys.exit(main())